apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-deployments-without-requests
spec:
  validationFailureAction: Enforce
  rules:
  - name: deny-deployments-without-requests
    match:
      resources:
        kinds:
        - Deployment
    validate:
      message: "Resource requests are required for deployments."
      pattern:
        spec:
          template:
            spec:
              containers:
              - resources:
                  requests: {}