- name: Make Git commit locally
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Clone the repository
      git:
        repo: https://github.com/alperencelik/sample-java-app-challenge.git
        dest: /tmp/sample-java-app-challenge
        version: HEAD
    - name: Update the version
      replace:
        path: /tmp/sample-java-app-challenge/gitops/sample-java-app/values.yaml
        regexp: 'tag: .+$'
        replace: 'tag: {{ COMMIT_SHA }}' 

    - name: Stage changes
      shell: cd /tmp/sample-java-app-challenge && git add . && git commit -m "Update version"
    - name: Push changes
      shell: cd /tmp/sample-java-app-challenge && git push https://{{ GITHUB_TOKEN }}@github.com/alperencelik/sample-java-app-challenge.git 