apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAhFNsdJYGlg0sQUh5AweHgy0vvfe+raJv9JxryUcDVpeLUayIKSXBwVOORKEbjMrj9pJB5Cz0oi+IXRPWPWrf3ZVu5H+N1UY71d7fGQgN1ktdi/jGMdWPSBORO/qdc/I0M1pq7vbdZd6pzxMuvCWVxCqMoVBCSD5+BoIOWreS4Lk54I14G58FmwknUxZPPVN89u0J5FZEQkZsACGFoUlBVEWBjwJs0BVlv07mo/hbRR3NIloElisUvkdVLGhfsUmXV8gGkpYuWV1MZ+o7mwb0LlYwoWP3M49Khr+5gCIeUMisJp/Wkt5rX6YOuyobJH5JNnZiolMI2iVkDeo/qBGxqZE+1ree7ylciyihaX1dLons4ry7JZxjn/X3XRYZk0VZSjE82HbSaj1Wk0nc7h0ZvMhZT/vrVdYhRv43h3d+TOvFpn3D3OcGjIo+2fkMi217qnCQseCJ/3s1ArAWH+J5jjHfcineiYW9fq7EQLHWx+5w28CsYqANdw49omwXoTDk1UsDuw+Wy88VO3Q+GVwM4JFQaprdscWhV7FhXwrqtQmlvOa3z7V457aQNW6IArGqmlguDhAtSbxRpYqMD0FcqTc40nD9l7SQvpao03yBqDu3FE8uwUDdYwTJIFgWhl3W14MJ2pCrnuhmksWHC/NTFMMl3mjo2luw+r5ibOJum3fsIGyjcwIu3sawFP2hN675W2VU1VcwARkgPPTy0bFchlZ82mFKra0zdt/Xs5tN9WqgeKlR2CzQg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque