apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCmxVX4jsNMOuK5zrJi7bP4ASFQYvvmBdhdVWk4053caspUe6BgTA0zNwfHu1ymVRpJ0Yv4W3uB3HiW4ByUa4ojkiVCkzzFoag1E2vt0/tCTZKyIpmy4pDVoZ+aT508Lv47LW7G2RBp8eheznL5FOatNR0s4s4dY+Hs8/Oe/Q5Eq6Z98aatzd2ykMwozxRENhT8i1PBz+Gy2e6VBDNhUXf1DPnNNzJEj6Xckd6Xa47i28rslCI+myUeKlZewiyhXd+4ZgU8bZbx9qCyf6lMnXuST45yZ/nbLbR2uB1Z1hl1sz09P8QcDqe4+kxIqSMtrVPp4hkygFx6sJzrHwSO2ACgBbS4z5lzdOKIfWCVwn9+rXWXbnNNNNcrW8eECnSQKT/nKalN2v3vv4p4GUb4Ate6Ug50Yb0eGrBdeuYQ9q68Lx9/rzrFs0H7TC8N/ERrg4+hOLxizw0HOrtG6y4APQIbUn0/9kpC9xDEwgnpgIbq0eXpqdNBWIgf0lqQsf5u6tu8+2BkKnvqAdvZ0ALHvXy1XQQo+gvefqX6sCMlwvtPQzMThRpiUrhI2L50WTaILekSXM3hapbnz4gMzqSKn4CHcE0/xZOI1eBwMoHc3GNNWuxJICV3ROsip3G2KBJj4TVI9YNMHibGrwJg225hBbAO/fllROKffuwH1zlXiJhMUM8Yeliy7BhCEkDy9npXf4FRw2LO4F9LcWjbAlibO36pKewk704Lsm/zBGVWdkEIvavoVsdhvmFz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque